winget install -e -h \
    Mozilla.Firefox;\
    qbittorrent.qbittorrent;\
    surfshark.surfshark;\
    7zip.7zip;\
    Python.Python.3.12;\
    Rustlang.Rustup;\
    Microsoft.VisualStudioCode;\
    Obsidian.Obsidian;\
    Valve.Steam;\
    Spotify.Spotify;\
    Git.Git;\
    Discord.Discord;\
    Microsoft.WindowsTerminal;\
    Stremio.Stremio;\
    Microsoft.PowerToys;\
    Syncthing.Syncthing;\
    vivaldi.vivaldi;\
    voidtools.Everything;\
    JanDeDobbeleer.OhMyPosh;\
    Telegram.TelegramDesktop;\
    Google.PlatformTools;\
    Armin2208.WindowsAutoNightMode;\
    Foxit.PhantomPDF;\
    WerWolv.ImHex;\
    AntibodySoftware.WizTree
